interfaces/overview/example.env
interfaces/overview/src/app/app.module.ts
interfaces/overview/src/app/mocks/api.mock.ts
interfaces/overview/src/app/mocks/mock-data.interceptor.ts
interfaces/overview/src/app/mocks/mock-data.module.ts
interfaces/overview/src/app/services/api.service.ts
interfaces/overview/src/environments/environment.prod.ts.template.js
interfaces/overview/src/environments/environment.ts

- configurable via .env
- fallback when API_URL is missing

Add MockData-interceptor to use during development

---

services/IBF-pipeline/Dockerfile.template
services/IBF-pipeline/README.md
services/IBF-pipeline/pipeline/lib/cronJob/processDynamicDataPostgres.sql
services/IBF-pipeline/pipeline/lib/setup/processStaticDataPostgres.sql

small bug fixes to run the pipeline @jannisvisser please review

add context to docker, fix dependencies in SQL, update README

---

interfaces/overview/package-lock.json
interfaces/overview/package.json
interfaces/overview/src/app/components/map/map.component.html
interfaces/overview/src/app/components/map/map.component.ts
interfaces/overview/src/app/components/matrix/matrix.component.html
interfaces/overview/src/app/components/matrix/matrix.component.ts
interfaces/overview/src/app/components/timeline/timeline.component.html
interfaces/overview/src/app/components/timeline/timeline.component.scss
interfaces/overview/src/app/components/timeline/timeline.component.spec.ts
interfaces/overview/src/app/components/timeline/timeline.component.ts
interfaces/overview/src/app/pages/map/map.page.html
interfaces/overview/src/app/pages/map/map.page.ts
interfaces/overview/src/app/pages/overview/overview.page.html
interfaces/overview/src/app/services/map.service.ts
interfaces/overview/src/app/services/timeline.service.spec.ts
interfaces/overview/src/app/services/timeline.service.ts
interfaces/overview/src/app/shared.module.ts

https://dev.azure.com/redcrossnl/IBF%20System/_workitems/edit/2639/

feat: timeline and setup layer subscribers

---

interfaces/overview/src/app/components/map/map.component.ts
interfaces/overview/src/app/components/timeline/timeline.component.html
interfaces/overview/src/app/components/timeline/timeline.component.scss
interfaces/overview/src/app/models/country.model.ts
interfaces/overview/src/app/services/map.service.ts
interfaces/overview/src/app/services/timeline.service.ts
services/API-service/src/data/data.service.ts
services/API-service/src/sql/IBF-database-scripts.sql
services/IBF-pipeline/pipeline/lib/cronJob/dynamicDataDb.py
services/IBF-pipeline/pipeline/lib/cronJob/glofasdata.py
services/IBF-pipeline/pipeline/lib/cronJob/processDynamicDataPostgresTrigger.sql

Country Dropdown

---

interfaces/IBF-dashboard/src/app/services/aggregates.service.ts
interfaces/IBF-dashboard/src/app/services/map.service.ts

@gulfaraz Is this commit message correct for Conventional Commit?

AB#5527 feat: show exposed pop. by default if trigger

---

interfaces/IBF-dashboard/src/app/services/map.service.ts

Reverts rodekruis/IBF-system#568

Revert "Ruben feat load dynamically active"

---

services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.spec.ts
services/API-service/src/api/eap-actions/dto/eap-action.dto.ts
services/API-service/src/api/eap-actions/eap-action-status.entity.ts
services/API-service/src/api/eap-actions/eap-actions.service.ts
services/API-service/src/api/user/dto/create-user.dto.ts
services/API-service/src/api/user/user.controller.spec.ts
services/API-service/src/api/user/user.controller.ts
services/API-service/src/api/user/user.interface.ts
services/API-service/src/api/user/user.model.ts
services/API-service/src/api/user/user.service.ts
services/API-service/src/app.controller.ts
services/API-service/src/main.ts
services/API-service/src/scripts/scripts.controller.ts
services/API-service/src/scripts/scripts.module.ts

1. style changes to the docs
2. supporting text to help navigate the docs
3. hides the schemas at the bottom of the docs
4. example endpoint with its response documented
5. extra configuration options which are visible on the code side but maybe not on the UI

Feat.api docs

---

services/API-service/src/scripts/json/countries.json
services/IBF-pipeline/pipeline/settings.py

Updated the EAP link for Zambia as per the comment in [AB#6090](https://dev.azure.com/redcrossnl/056030a3-96d2-4070-8718-48f602a2af75/_workitems/edit/6090)

fix: update zambia eap link AB#8207

---

services/IBF-pipeline/pipeline/lib/pipeline/glofasdata.py
services/IBF-pipeline/pipeline/settings.py

This reverts commit 87a101f351754dedbf362b4bb012d37b90d66225, reversing
changes made to 1752d360a97bfe663b1bf8dedf3da841c1c378e2.

Revert "Merge pull request #795 from rodekruis/feat.ftp"

---

README.md
docs/TROUBLESHOOT.md
services/IBF-pipeline/README.md

docs: to help while installation, guidline provided in troubleshoot file

---

interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.scss
interfaces/IBF-dashboard/src/assets/i18n/en.json
services/API-service/src/scripts/json/EAP-actions.json

Add-EAP-action-6134, Change-trigger-msg-6380, Change-title-to-bold-9117

---

services/API-service/src/api/point-data/dto/upload-asset-exposure-status.dto.ts

[AB#28548](https://dev.azure.com/redcrossnl/056030a3-96d2-4070-8718-48f602a2af75/_workitems/edit/28548)

fix: show correct key in dynamic point docs AB#28548

---

interfaces/IBF-dashboard/src/app/app.module.ts
interfaces/IBF-dashboard/src/app/services/auth.interceptor.service.ts

1. Sign out the user if the user has no access to any country.
2. Sign out the user if the user makes an unauthorized request.

fix: use auth interceptor

---

.github/workflows/workflow.yml

Update GitHub action versions in workflow and remove unused config

ci: workflow

---

.github/workflows/workflow.yml
docker-compose.yml

build: remove unused docker config

---

.github/workflows/workflow.yml
interfaces/IBF-dashboard/package.json

separate test and lint in dashboard ci

ci: separate test and lint in dashboard ci

---

docker-compose.yml

uses correct build directory as per angular 18 #1513

fix: use browser build directory

---

services/API-service/package-lock.json
services/API-service/package.json
services/API-service/src/api/country/country.service.ts
services/API-service/src/api/waterpoints/waterpoints.service.ts

- Remove `wkt-io-ts`
- Update `class-transformer`

refactor: wkt

---

package.json

Use `pre-commit` to perform `lint` check.

ci: add pre-commit lint

---

interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html

fix: remove debug variable

---

interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html

Same as https://github.com/rodekruis/IBF-system/pull/1572
1. I missed a spot.

fix: use unique id for for loop

---

e2e/Pages/ChatComponent.ts
e2e/tests/ChatSection/AllChatComponentsPresentNotrigger.spec.ts
interfaces/IBF-dashboard/src/app/components/about-btn/about-btn.component.html
interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/export-view/export-view.component.html
interfaces/IBF-dashboard/src/app/components/ibf-guide-button/ibf-guide-button.component.html
services/API-service/test/helpers/utility.helper.ts

Adds assertions for all elements in chat component.

Feat.add e2e test for chat section no trigger

---

.gitignore
e2e/.gitignore
e2e/Pages/AggregateComponenet.ts
e2e/Pages/DisasterTypeComponent.ts
e2e/Pages/TimelineComponent.ts
e2e/package-lock.json
e2e/package.json
e2e/playwright.config.ts
e2e/tests/AggregatesSection/AllAggregatesComponentsPresentNotrigger.spec.ts
e2e/tests/ChatSection/AllChatComponentsPresentNotrigger.spec.ts
e2e/tests/Dashboard/AllElementsPresentNoTrigger.spec.ts
e2e/tests/DisasterType/AllDisasterTypeComponentsPresentNotrigger.spec.ts
e2e/tests/Map/AllMapComponentsPresentNotrigger.spec.ts
e2e/tests/Timeline/TimelineComponentPresentNotrigger.spec.ts
e2e/tests/UserState/AllUserStateComponentsPresentNotrigger.spec.ts

Separates the test for Timeline and adds integration with qase

Feat.add reporter for playwright and qase

---

e2e/Pages/LoginPage.ts
e2e/Pages/UserStateComponent.ts
e2e/tests/UserState/SuccessfullyLogOut.spec.ts
interfaces/IBF-dashboard/src/app/pages/login/login.page.html

Adds logout test to test User State component's functionality

Feat.add e2e test for logout feature

---

WHAT_IS_NEW_IN_IBF.md
services/API-service/src/scripts/json/notification-info.json

- Update what is new in IBF
- Update to trigger statement South Sudan

chore: update what is new in IBF v0.274.1

---

services/API-service/src/api/typhoon-track/typhoon-track.service.ts

fix: don't break if closestToLand point missing

---

.github/workflows/workflow.yml

Update CI workflow to run tests when test files change.
1. As correctly identified out by @jannisvisser [here](https://github.com/rodekruis/IBF-system/pull/1700#issuecomment-2441922879).

ci: run tests when test files change

---

.github/workflows/workflow.yml

chore: define outputs

---

.github/actions/e2e/action.yml
.github/actions/integration/action.yml

Reverts rodekruis/IBF-system#1722
Hmm, it doesn't make a difference.. unclear why these tests are failing then though. @gulfaraz

Revert "ci: extend wait time startup"

---

interfaces/IBF-dashboard/src/app/services/point-marker.service.ts
tests/e2e/Pages/MapComponent.ts
tests/e2e/tests/Map/GloFAStaionsVisibleNoTrigger.spec.ts

Adds E2E test for no threshold in "No-trigger" mode

No alert threshold visible in no trigger

---

package.json

fix: version-nr

---

README.md
WHAT_IS_NEW_IN_IBF.md

chore: update whatsnew

---

package.json

The bump step keeps failing because of version-nr issues. Trying to align it now.

fix: version-nr to fix bump-step

---

package.json

fix: align version-nr again

---

services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-alert_threshold-3.json
services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-damage_estimation-3.json
services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-nr_affected_buildings-3.json
services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-nr_affected_clinics-3.json
services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-nr_affected_roads-3.json
services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-nr_affected_schools-3.json
services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-nr_affected_waterpoints-3.json
services/API-service/src/scripts/mock-data/flash-floods/MWI/trigger/Blantyre City/upload-population_affected-3.json
tests/integration/email/floods/email-ssd-floods.test.ts

fix: blantyre mock data adm3

---

package.json

Align version-nr in package.json. (Because the PR I merged only had a 'chore' commit, even though I wanted it to create a tag. So instead I made a manual release out of it. This PR is needed to make sure the code version-nr aligns again.)

chore: align version nr

---

WHAT_IS_NEW_IN_IBF.md

chore: update what's new AB#31856

---

interfaces/IBF-dashboard/package-lock.json
interfaces/IBF-dashboard/package.json
services/API-service/package-lock.json
services/API-service/package.json
tests/e2e/package-lock.json
tests/e2e/package.json

chore: update xlsx packages to resolve vulnerabilities

---

tests/e2e/Pages/AggregatesComponent.ts
tests/e2e/Pages/ChatComponent.ts
tests/e2e/tests/ChatSection/TriggerStateShouldHaveWarningEvents.spec.ts
tests/e2e/tests/DisasterType/SwitchBetweenDisasterType.spec.ts

Adds test that checks for amount of triggers (of any type) and compares it with the number of aggregated events.

Add e2e test for trigger warning in trigger state

---

services/API-service/src/api/notification/dto/send-notification.dto.ts
services/API-service/src/api/notification/email/email.service.ts
services/API-service/src/scripts/mock.controller.ts

[AB#32208](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32208)

chore: mark email subject as non-prod if applicable AB#32208

---

.github/dependabot.yml

See [AB#32221](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32221)

chore: no dependabot PRs for patch versions AB#32221

---

interfaces/IBF-dashboard/src/app/components/change-password-popover/change-password-popover.component.scss
interfaces/IBF-dashboard/src/app/components/change-password-popover/change-password-popover.component.ts
interfaces/IBF-dashboard/src/app/components/login-form/login-form.component.html
interfaces/IBF-dashboard/src/app/components/login-form/login-form.component.scss
interfaces/IBF-dashboard/src/app/components/login-form/login-form.component.ts
services/API-service/src/api/user/dto/create-user.dto.ts

Resolves [AB#32332](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32332)
1. I am open to better ways to fixing this. Maybe global style that solves both cases at once? And maybe something that resolves the root cause instead of "correcting" it which is maybe more what I did?
2. On the other hand, we also shouldn't spend too much time on this.

fix: no border on ion-input, also on focus

---

services/API-service/src/api/user/dto/create-user.dto.ts

[AB#32346](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32346)

fix: use null as default value for middle name

---

interfaces/IBF-dashboard/eslint.config.js
interfaces/IBF-dashboard/package-lock.json
interfaces/IBF-dashboard/package.json
interfaces/IBF-dashboard/src/app/components/login-form/login-form.component.spec.ts

[AB#31784](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/31784)
I added an eslint config for test files as they require a few exceptions.

Test.unit login form component

---

.github/workflows/workflow.yml

[AB#31892](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/31892)

chore: only bump version if all tests succeed AB#31892

---

.github/workflows/workflow.yml
interfaces/IBF-dashboard/src/app/components/login-form/login-form.component.spec.ts

Test PR with delibaretedly failing test to test if bump-version now fails because of this. Will merge this and then revert later.

fix: test commit with failing test AB#31892

---

.github/workflows/workflow.yml
interfaces/IBF-dashboard/src/app/components/login-form/login-form.component.spec.ts

Reverts rodekruis/IBF-system#1888

Revert "fix: test commit with failing test AB#31892"

---

.github/workflows/workflow-pull_request.yml
.github/workflows/workflow-push.yml

[AB#32464](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32464)

chore: run checks on PR and bump version on merge AB#32464

---

.github/workflows/workflow-push.yml
package.json

chore: new try AB#32464

---

.github/workflows/workflow-push.yml
package.json

chore: ignore status checks on push via deploy key AB#32464

---

.github/workflows/workflow-push.yml
package.json

Chore.split checks and bump

---

interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/tooltip/tooltip.component.html
tests/e2e/Pages/ChatComponent.ts
tests/e2e/Pages/DashboardPage.ts
tests/e2e/tests/ChatSection/ChatInfoButtonOpenPopOver.spec.ts

Adds test for validating info icons by warnings in chat section.

Add E2E test for: [Trigger] Info icon is clickable and opens popover

---

services/API-service/src/api/country/country.service.spec.ts
services/API-service/src/api/country/country.service.ts

[AB#31781](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/31781)
1. I did not mock private functions based on [dev chat](https://teams.microsoft.com/l/message/19:bdb9d621f18c48c7917e545bf6d7aabe@thread.v2/1736170063678?context=%7B%22contextType%22%3A%22chat%22%7D).
2. No single expectation of a function exists. The functions are implemented to perform multiple data changes so I added an assert for each.
3. I skipped `getBoundingBoxWkt` because it is a single TypeORM statement.

test: unit tests for country module

---

tests/integration/package.json

Integration package name should not be e2e.

chore: rename package name to integration

---

services/API-service/package-lock.json
services/API-service/package.json

Remove slug dependency as it's unused.

chore: remove slug dependency

---

services/API-service/src/api/admin-area/admin-area.service.ts

See [AB#33076](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/33076)

fix: filter admin-areas on eventName AB#33076

---

tests/e2e/Pages/MapComponent.ts
tests/e2e/Pages/TimelineComponent.ts
tests/e2e/Pages/UserStateComponent.ts
tests/e2e/testData/testData.enum.ts
tests/e2e/tests/ScenarioTrigger.spec.ts
tests/e2e/tests/TimelineComponent/TimelineComponentNotClickable.ts

Adds e2e test for validating timeline to be disabled in trigger flood scenario

Add test case and update trigger scenarios

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/chat/chat.component.ts
interfaces/IBF-dashboard/src/app/models/country.model.ts
interfaces/IBF-dashboard/src/app/services/eap-actions.service.ts
interfaces/IBF-dashboard/src/app/services/timeline.service.ts
services/API-service/migration/1739191789807-RemoveEndOfMonthPipeline.ts
services/API-service/src/api/country/country-disaster.entity.ts
services/API-service/src/api/country/country.service.ts
services/API-service/src/api/country/dto/add-countries.dto.ts
services/API-service/src/scripts/interfaces/country.interface.ts
services/API-service/src/scripts/json/countries.json
services/API-service/src/scripts/mock-helper.service.ts
tests/integration/helpers/API-service/dto/create-country.dto.ts

See [AB#33425](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/33425)

Chore.remove endofmonthpipeline

---

services/API-service/src/api/notification/email/email.service.ts
services/API-service/src/api/notification/notification.service.ts
services/API-service/src/api/notification/whatsapp/whatsapp.service.ts
services/API-service/src/api/process-pipeline/process-pipeline.controller.ts
services/API-service/src/api/process-pipeline/process-pipeline.service.ts
services/API-service/src/scripts/mock.service.ts
services/API-service/src/scripts/scripts.controller.ts
tests/e2e/helpers/utility.helper.ts
tests/integration/helpers/utility.helper.ts

- Rename isApiTest to noNotifications
- No further refactors wrt ths. Default values per endpoint remain as implemented earlier.
- Some minor other method renames included.

refactor: rename isApiTest AB#33896

---

interfaces/IBF-dashboard/src/app/components/date-button/date-button.component.ts
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/app/components/event-switcher/event-switcher.component.ts
interfaces/IBF-dashboard/src/app/components/map/map.component.ts
interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.html
interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.scss
interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.ts
interfaces/IBF-dashboard/src/app/services/timeline.service.ts
interfaces/IBF-dashboard/src/app/types/lead-time.ts
interfaces/IBF-dashboard/src/app/types/timeline-state.ts
services/API-service/src/api/event/event.service.ts

- This started out as making timeline unclickable for drought
- Quickly evolved into making unclickable for all disaster-types (aligned with Gal wrt typhoon), and malaria seems fine as well
- Which in turn opened up an opportunity for quite major refactor / code reduction in the timeline.service. This turned into quite the monster to really wrap up all loose ends..
- See [AB#33408](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/33408)

Feat.unclickable timeline

---

services/API-service/migration/1740565983568-ProcessUncoveredDatamodelChanges.ts
services/API-service/migration/1740565983568-WarningRefactorToProd.ts
services/API-service/src/api/admin-area-data/admin-area-data.entity.ts

- This PR is directly on master, does not relate to the other (more front-end) PRs.
- See [AB#33405](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/33405)

Migrations from testing on prod data

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/chat/chat.component.ts
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/app/models/country.model.ts
interfaces/IBF-dashboard/src/assets/i18n/en.json
services/API-service/migration/1740498589278-RenameForecastSource.ts
services/API-service/src/api/country/country-disaster.entity.ts
services/API-service/src/api/country/country.service.ts
services/API-service/src/api/country/dto/add-countries.dto.ts
services/API-service/src/api/event/event.service.ts
services/API-service/src/scripts/interfaces/country.interface.ts
services/API-service/src/scripts/json/countries.json
tests/integration/helpers/API-service/dto/create-country.dto.ts

- Builds upon #2008 
- See [AB#33901](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/33901) for details
- Moving remaining design discrepancies to next item [AB#32042](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32042)

Feat.event speech bubble

---

services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.controller.ts
services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.ts
services/API-service/src/api/admin-area/admin-area.controller.ts
services/API-service/src/api/admin-area/admin-area.service.ts
services/API-service/src/api/eap-actions/eap-actions.controller.ts
services/API-service/src/api/event/event.controller.ts
services/API-service/src/api/lines-data/lines-data.controller.ts
services/API-service/src/api/point-data/point-data.controller.ts
services/API-service/src/api/process-pipeline/process-pipeline.controller.ts
services/API-service/src/api/typhoon-track/typhoon-track.controller.ts
services/API-service/src/api/user/user.controller.ts

See [AB#34169](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34169)

docs: review current user roles + include EXTERNALLY USED label AB#34169

---

services/API-service/migration/1741186768255-UserTrigger.ts
services/API-service/src/api/event/dto/event-place-code.dto.ts
services/API-service/src/api/event/event-place-code.entity.ts
services/API-service/src/api/event/event.controller.ts
services/API-service/src/api/event/event.service.ts
services/API-service/src/api/user/user.entity.ts
services/API-service/src/api/user/user.service.spec.ts
services/API-service/src/shared/data.model.ts

[AB#34109](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/34109)
1. Rename `stopped` to `userTrigger`
2. Rename `manuallyStoppedDate` to `userTriggerDate`
3. New API `set-trigger`
4. Remove old API `toggle-stopped-trigger`
Tests and docs will be updated in [AB#34121](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/34121) and [AB#34123](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/34123) respectively.

feat: rename stopped to userTrigger

---

services/API-service/src/api/event/event.service.ts

See [AB#34304](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34304)

fix: rm leadtime filter on deleteDuplicates in alerts-per-lead-time

---

interfaces/IBF-dashboard/src/app/components/event-switcher/event-switcher.component.html
tests/e2e/Pages/ChatComponent.ts
tests/e2e/Pages/MapComponent.ts
tests/e2e/tests/ChatComponent/ChatComponentTriggeredAreasList.ts
tests/e2e/tests/tests.spec.ts

Adds test for navigating to early action's protocol list

Add e2e test: "Click on area in triggered areas list in chat"

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/chat/chat.component.scss
interfaces/IBF-dashboard/src/app/components/chat/chat.component.ts
interfaces/IBF-dashboard/src/app/components/date-button/date-button.component.html
interfaces/IBF-dashboard/src/app/components/date-button/date-button.component.scss
interfaces/IBF-dashboard/src/app/components/dialogue-turn/dialogue-turn.component.html
interfaces/IBF-dashboard/src/app/components/dialogue-turn/dialogue-turn.component.scss
interfaces/IBF-dashboard/src/app/components/dialogue-turn/dialogue-turn.component.ts
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.scss
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/assets/i18n/en.json

- Builds upon #2030 
- Front-end changes based on conversation with Tal and https://www.figma.com/design/NobGDc5CuEAu1BlsfA4PvI/%F0%9F%93%9A-IBF-component-library?node-id=1-2&p=f&t=eNmCtAgGxbmPAFmx-0
- See [AB#34118](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34118)

Feat.chat design

---

interfaces/IBF-dashboard/src/app/components/date-button/date-button.component.html
interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.html
interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.scss
interfaces/IBF-dashboard/src/app/pages/dashboard/dashboard.page.scss
interfaces/IBF-dashboard/src/app/services/timeline.service.ts
services/API-service/src/scripts/mock.service.ts

- Builds upon #2034 
- Aligns timeline with new design 
- Drop disabled look
- Use same styling for warning/trigger except for triangle icon being solid/outlined
- other details
- See [AB#34303](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34303), also for what's not done (yet)

Feat.timeline design

---

services/API-service/src/api/event/event.service.ts

See [AB#34355](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34355)

Fix.timestamp check

---

interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.spec.ts
services/API-service/src/api/event/event.service.spec.ts
tests/integration/helpers/API-service/enum/alert-level.enum.ts
tests/integration/helpers/utility.helper.ts
tests/integration/tests/events/set-trigger.test.ts

Automated tests around 'set trigger'
- integration test on /set-trigger
- backend unit test on 'setTrigger()
- frontend unit test on 'open popover'
- created separate item for e2e test
- see [AB#34121](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34121)

Test.set trigger

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.spec.ts
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/app/components/event-switcher/event-switcher.component.scss
interfaces/IBF-dashboard/src/app/components/set-trigger-popover/set-trigger-popover.component.html
interfaces/IBF-dashboard/src/app/components/set-trigger-popover/set-trigger-popover.component.ts
interfaces/IBF-dashboard/src/app/models/country.model.ts
interfaces/IBF-dashboard/src/assets/i18n/en.json
interfaces/IBF-dashboard/src/global.scss
services/API-service/src/api/country/country-disaster.entity.ts
services/API-service/src/api/event/event.service.ts
services/API-service/src/scripts/json/countries.json

- First set of changes based on design review wrt event-speech-bubble.
- See [AB#34124](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34124) for exactly what's done and not.

Feat.design review event bubble

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/set-trigger-popover/set-trigger-popover.component.html
interfaces/IBF-dashboard/src/app/components/set-trigger-popover/set-trigger-popover.component.scss
interfaces/IBF-dashboard/src/app/components/set-trigger-popover/set-trigger-popover.component.ts
interfaces/IBF-dashboard/src/app/components/tooltip/tooltip.component.ts
interfaces/IBF-dashboard/src/app/components/user-state/user-state.component.html
interfaces/IBF-dashboard/src/assets/i18n/en.json
interfaces/IBF-dashboard/src/global.scss
interfaces/IBF-dashboard/src/theme/variables.scss

[AB#34124](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/34124)
1.  Content should have horizontal padding + align buttons equal width > Gulfaraz > Skipping because the existing html and css are _interesting_.
1.  Button should align to the width of the content > Gulfaraz > Skipping because the existing html and css are _interesting_.
1.  Reduce space between _Set trigger_ and _Back to national view_ buttons (in Ethiopia drought) > Gulfaraz  > Skipping because the existing html and css are _interesting_.
1.  Base font should be Open Sans with Montserrat for headers > Gulfaraz > Surprisingly easy to switch the base font. Made the title Montserrat to test if we can swtich fonts easily.
1.  Text in information popup should have smaller line height (also check other information popups) …

feat: design review prioritized

---

WHAT_IS_NEW_IN_IBF.md
services/API-service/src/api/admin-area/admin-area.service.ts
services/API-service/src/scripts/json/notification-info.json

- Fix production bug with area filtering.
- Includes also unrelated: updated what's new + slighty updated trigger statement LSO

fix: area filtering bug AB#34732

---

services/API-service/src/main.ts

After this PR is merged, swagger will automatically authorize the user on a successful login API response.

feat: swagger auth

---

services/API-service/src/api/notification/notification.service.ts

- Based on integration test: we should not send email for ongoing events
- Implemented by making the current flash-flood behaviour generic to all disaster-types. So including the exception for when an event starts as ongoing. I think it's fair that we apply this to all ongoing events. 
- I tested a mock LSO drought in Feb (email) and then in Mar with removeEvents=false (no email)

feat: make no email on ongoing generic

---

example.env

Add placeholder mailchimp api key to example env.
The API service throws an error on startup if this key is empty.

chore: add placeholder mailchimp api key to example env

---

services/API-service/src/scripts/scripts.controller.ts
services/API-service/src/scripts/scripts.module.ts
services/API-service/src/scripts/seed-init.ts
tests/e2e/helpers/utility.helper.ts
tests/integration/helpers/utility.helper.ts
tests/integration/package.json
tests/integration/tests/all.test.ts
tests/integration/tests/community-notification/community-notification.test.ts
tests/integration/tests/country/create-country.test.ts
tests/integration/tests/email/drought/email-uga-drought.test.ts
tests/integration/tests/email/flash-flood/email-mwi-flash-flood.test.ts
tests/integration/tests/email/floods/email-ssd-floods.test.ts
tests/integration/tests/email/floods/email-uga-floods.test.ts
tests/integration/tests/email/malaria/email-eth-malaria.test.ts
tests/integration/tests/email/typhoon/email-phl-typhoon.test.ts
tests/integration/tests/events/process.test.ts
tests/integration/tests/events/set-trigger.test.ts
tests/integration/tests/typhoon-track/typhoon-track.test.ts
tests/integration/tests/users/manage-users.test.ts

- Make lines-data optional in seed > not included in test seed
- Restructure integration tests to one suite with just one resetDb

Chore.decrease test seed time

---

interfaces/IBF-dashboard/eslint.config.js
interfaces/IBF-dashboard/package-lock.json
interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.spec.ts
interfaces/IBF-dashboard/src/app/components/areas-of-focus-summary/areas-of-focus-summary.component.spec.ts
interfaces/IBF-dashboard/src/app/components/chat/chat.component.spec.ts
interfaces/IBF-dashboard/src/app/components/community-notification-photo-popup/community-notification-photo-popup.component.spec.ts
interfaces/IBF-dashboard/src/app/components/community-notification-popup/community-notification-popup.component.spec.ts
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.spec.ts
interfaces/IBF-dashboard/src/app/components/event-switcher/event-switcher.component.spec.ts
interfaces/IBF-dashboard/src/app/components/export-view-popover/export-view-popover.component.spec.ts
interfaces/IBF-dashboard/src/app/components/export-view/export-view.component.spec.ts
interfaces/IBF-dashboard/src/app/components/ibf-guide-button/ibf-guide-button.component.spec.ts
interfaces/IBF-dashboard/src/app/components/ibf-guide-popover/ibf-guide-popover.component.spec.ts
interfaces/IBF-dashboard/src/app/components/layer-control-info-popover/layer-control-info-popover.component.spec.ts
interfaces/IBF-dashboard/src/app/components/matrix/matrix.component.spec.ts
interfaces/IBF-dashboard/src/app/components/tooltip/tooltip.component.spec.ts
interfaces/IBF-dashboard/src/app/components/user-state/user-state.component.spec.ts
interfaces/IBF-dashboard/src/app/mocks/alert-areas.mock.ts
interfaces/IBF-dashboard/src/app/pages/dashboard/dashboard.page.spec.ts
interfaces/IBF-dashboard/src/app/pages/login/login.page.spec.ts
interfaces/IBF-dashboard/src/app/services/alert-area.service.ts
interfaces/IBF-dashboard/src/app/types/alert-area.ts
services/API-service/eslint.config.js
services/API-service/src/api/event/event.service.ts
services/API-service/src/scripts/json/EAP-actions.json
services/API-service/src/shared/data.model.ts
tests/e2e/eslint.config.js
tests/e2e/package-lock.json
tests/e2e/package.json
tests/integration/eslint.config.js

- solve code bug which caused area list of wrong event to show
- solved data mistake with months of seasons being switched around
- solved other bug around early actions
- added eslint rules to prohibit focused tests

fix: redefine monthLong bug AB#35178

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.ts
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/app/components/event-switcher/event-switcher.component.ts
interfaces/IBF-dashboard/src/app/components/map/map.component.ts
interfaces/IBF-dashboard/src/app/mocks/event-state.mock.ts
interfaces/IBF-dashboard/src/app/pages/dashboard/status-report/status-report.page.ts
interfaces/IBF-dashboard/src/app/services/api.service.ts
interfaces/IBF-dashboard/src/app/services/event.service.ts
interfaces/IBF-dashboard/src/app/services/point-marker.service.ts
interfaces/IBF-dashboard/src/app/types/event-state.ts
services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.ts
services/API-service/src/api/admin-area/services/event-area.service.ts
services/API-service/src/api/event/event.controller.ts
services/API-service/src/api/event/event.service.ts
services/API-service/src/api/notification/dto/notification-date-per-event.dto.ts
services/API-service/src/api/notification/email/email.service.ts
services/API-service/src/api/notification/notification-content/notification-content.service.ts
services/API-service/src/api/notification/notification.service.ts
services/API-service/src/api/notification/whatsapp/whatsapp.service.ts
services/API-service/src/shared/data.model.ts
tests/integration/helpers/utility.helper.ts
tests/integration/tests/events/set-trigger.test.ts
tests/integration/tests/typhoon-track/typhoon-track.test.ts

Rename EventSummary (and related) to Event. [AB#35336](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/35336)

refactor: rename eventsummary AB#35336

---

services/API-service/src/api/admin-area/admin-area.service.ts
services/API-service/src/api/admin-area/services/event-area.service.ts
tests/integration/tests/admin-areas/admin-areas.test.ts
tests/integration/tests/admin-areas/aggregates.test.ts
tests/integration/tests/all.test.ts

[AB#35334](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/35334)
This PR adds 2 simple integration tests on the /admin-areas and /admin-areas/aggregates endpoints.
I stopped at the basic tests based on [this comment](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/35225#14729479). It makes sense to investigate for potential refactors before adding more tests.

test: add integration tests for GET admin-areas and admin-areas/aggregates

---

README.md

Remove https from localhost URL in README.

docs: remove https from localhost link

---

services/API-service/.gitignore
services/API-service/ormconfig.ts
services/API-service/src/api/admin-area-data/admin-area-data.service.ts
services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.ts
services/API-service/src/api/notification/email/email.service.ts
services/API-service/src/api/notification/lookup/lookup.service.ts
services/API-service/src/api/notification/whatsapp/auth.middlewareTwilio.ts
services/API-service/src/api/notification/whatsapp/whatsapp.service.ts
services/API-service/src/app.module.ts
services/API-service/src/config.ts
services/API-service/src/cronjob/cronjob.service.ts
services/API-service/src/middleware/logger.middleware.ts
services/API-service/src/scripts/geoserver-sync.service.ts
services/API-service/src/scripts/mock-helper.service.ts
services/API-service/src/scripts/mock.service.ts
services/API-service/src/scripts/seed-admin-area-data.ts
services/API-service/src/scripts/seed-init.ts
services/API-service/src/scripts/seed-prod.ts
services/API-service/src/typeorm.logger.ts

Add logging to help understand what is happening in API-service. These logs were needed to help debug the Lesotho drought pipeline.

build: backend logs

---

services/API-service/ormconfig.ts

Configure ormconfig as recommended in [the official docs](https://node-postgres.com/features/ssl#self-signed-cert).

fix: self-signed certificate

---

docker-compose.ci.yml
services/API-service/package.json
services/API-service/src/scripts/seed-init.ts

Runs seed init automatically for dev setup.

build: auto run seed init for devs

---

tests/e2e/helpers/utility.helper.ts
tests/e2e/tests/tests.spec.ts
tests/integration/helpers/utility.helper.ts
tests/integration/tests/admin-areas/admin-areas.test.ts
tests/integration/tests/admin-areas/aggregates.test.ts
tests/integration/tests/community-notification/community-notification.test.ts
tests/integration/tests/email/drought/test-drought-scenario.helper.ts
tests/integration/tests/email/flash-flood/test-flash-flood-scenario.helper.ts
tests/integration/tests/email/floods/test-flood-scenario.helper.ts
tests/integration/tests/email/malaria/test-malaria-scenario.helper.ts
tests/integration/tests/email/typhoon/test-typhoon-scenario.helper.ts
tests/integration/tests/events/get-events.test.ts
tests/integration/tests/events/process-events.test.ts
tests/integration/tests/events/set-trigger.test.ts
tests/integration/tests/typhoon-track/typhoon-track.test.ts
tests/integration/tests/users/users.api.ts

This PR updates the mock function to have optional params to match the API.
I changed the function order in users because I rewrote the function for `PATCH /api/user` before I realized it was already in the file. I was comparing with the Swagger docs, so I matched that order.

test: refactor mock and notify

---

interfaces/IBF-dashboard/package-lock.json

This automatic change happened locally, so committed.

chore: automatic update package-lock

---

interfaces/IBF-dashboard/package-lock.json
interfaces/IBF-dashboard/package.json

chore: upgrade esbuild

---

.github/actions/e2e/action.yml
.gitignore
example.env
interfaces/IBF-dashboard/src/app/components/matrix/matrix.component.html
services/API-service/src/api/metadata/layer-metadata.entity.ts
services/API-service/src/scripts/seed-point-data.ts
tests/e2e/Pages/MapComponent.ts
tests/e2e/testData/MalawiFlashFloodsNoTrigger.json
tests/e2e/testData/MalawiFlashFloodsTrigger.json
tests/e2e/testData/UgandaFloodsTrigger.json
tests/e2e/testData/types.ts
tests/e2e/tests/MapComponent/MapComponentLayersDefault.ts
tests/e2e/tests/MapComponent/MapComponentLinesLayers.ts
tests/e2e/tests/tests.spec.ts
tests/integration/tests/all.test.ts
tests/integration/tests/community-notification/community-notification.api.ts
tests/integration/tests/community-notification/community-notification.test.ts
tests/integration/tests/point-data/get-point-data.test.ts
tests/integration/tests/point-data/point-data.api.ts

Automated tests around exposable assets.
- e2e test on testing geoserver rendering of lines layers
- integration test on GET /point-data of exposable assets
1. See [AB#36050](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/36050)

exposable assets: automated tests AB#36050

---

docker-compose.yml

See [AB#36431](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/36431)
1. This code change was first manually tried on ibf-test
2. Already merging this PR to test complete result on ibf-test again.

fix: geoserver remote login AB#36431

---

services/API-service/src/api/admin-area/admin-area.controller.ts
services/API-service/src/api/admin-area/admin-area.service.ts
services/API-service/src/api/admin-area/dto/admin-area.dto.ts
tests/integration/tests/admin-areas/admin-areas-delete.test.ts
tests/integration/tests/admin-areas/admin-areas.api.ts
tests/integration/tests/admin-areas/admin-areas.assertions.ts
tests/integration/tests/admin-areas/admin-areas.test.ts
tests/integration/tests/admin-areas/aggregates.test.ts
tests/integration/tests/admin-areas/event-admin-areas.assertions.ts
tests/integration/tests/admin-areas/event-admin-areas.test.ts
tests/integration/tests/all.test.ts

Add `/admin-areas` to read admin areas from IBF.
This PR is linked to https://github.com/rodekruis/IBF-river-flood-pipeline/pull/33, https://github.com/rodekruis/IBF-drought-pipeline/pull/22, and [AB#35877](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/35877).
I was unable to find any other pipeline affected by this change.

feat: admin areas

---

.github/dependabot.yml

This PR updates the dependabot groups to reduce the number of maintenance PRs.

ci: update dependabot groups

---

services/API-service/src/api/user/user.entity.ts
services/API-service/src/api/user/user.service.ts
services/API-service/src/scripts/seed-init.ts
services/API-service/src/scripts/seed-prod.ts

This PR builds on changes proposed by Copilot in https://github.com/rodekruis/IBF-system/pull/2341
Copilot solved the problem, but it took a few reviews, which created minor gaps which were easier to solve manually.

Automatically update DUNANT password from env file during deployment

---

services/API-service/src/api/user/user.entity.ts
services/API-service/src/scripts/seed-helper.ts
services/API-service/src/scripts/seed-init.ts
services/API-service/src/scripts/seed-prod.ts

This PR fixes a duplication error caused by https://github.com/rodekruis/IBF-system/pull/2348

fix: remove countries before update to avoid duplication errors

---

interfaces/IBF-dashboard/src/app/analytics/analytics.enum.ts
interfaces/IBF-dashboard/src/app/analytics/analytics.service.ts
interfaces/IBF-dashboard/src/app/components/layer-control-info-popover/layer-control-info-popover.component.spec.ts
interfaces/IBF-dashboard/src/app/components/layer-control-info-popover/layer-control-info-popover.component.ts
interfaces/IBF-dashboard/src/app/pages/dashboard/status-report/status-report.page.html
interfaces/IBF-dashboard/src/shared/utils.ts

This PR downloads CSV files instead of geojson, tracks download and upload clicks, sets analytics user context, removes default border for no alert.

fix: download csv

---

services/API-service/src/scripts/mock-data/floods/ETH/scenarios.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/alerts-per-lead-time.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/glofas-station.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/triggers-per-lead-time.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-alert_threshold-2.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-alert_threshold-3.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-forecast_severity-2.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-forecast_severity-3.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-forecast_trigger-2.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-forecast_trigger-3.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-population_affected-2.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-population_affected-3.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-population_affected_percentage-2.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/G1074/upload-population_affected_percentage-3.json
services/API-service/src/scripts/mock-data/floods/ETH/warning/glofas-stations-no-alert.json

Add warning mock scenario for Ethiopia flood.

feat: add warning scenario for eth flood
