.gitignore
interfaces/overview/.gitignore
services/API-service/.gitignore
services/IBF-pipeline/.gitignore

There is some duplication across all files, but this way each 'component' (or sub-folder) can be used independently in IDE/editors

Align all .gitignore files

---

interfaces/IBF-dashboard/src/app/mocks/mock-scenario.interceptor.ts
interfaces/IBF-dashboard/src/app/services/api.service.ts
interfaces/IBF-dashboard/src/environments/environment.ts

@jannisvisser @RubenGeo I've updated the api_url config value to keep the trailing slash consistent.
i.e.) to use `https://ibf.510.global/api` instead of `https://ibf.510.global/api/`

refactor: remove trailing slash in api url

---

services/API-service/src/scripts/seed-helper.ts

This change allows running seed on a non-empty database.

fix: drop table if exists

---

services/API-service/src/api/waterpoints/waterpoints.service.ts

the old waterpoints dataset is inaccessible so I switched to a [new waterpoints dataset](https://data.waterpointdata.org/dataset/Water-Point-Data-Exchange-WPDx-Basic-/jfkt-jmqa). Tested on Uganda, Zambia, Ethiopia, Kenya and Zimbabwe as per [layer-metadata.json](https://github.com/rodekruis/IBF-system/blob/de8b518760e55d19d478e62eaffac18605c437d9/services/API-service/src/scripts/json/layer-metadata.json#L89). It's slow on Uganda because it's loading 95k+ waterpoints, it's fine for the other countries.

fix: switch to new waterpoints dataset AB#9112

---

services/API-service/src/api/notification/email/email-template.service.ts

icon for max warning should use trigger icon instead of causing an error

fix: icon for max warning should use trigger icon

---

services/API-service/src/scripts/json/EAP-actions.json

We should not have Dengue units for Malaria EAP. Use MEMU until we find the right term.

fix: use MEMU for malaria

---

services/API-service/src/api/notification/email/email-template.service.ts
services/API-service/src/api/notification/email/html/table-event.html

fix: email design review changes

---

services/API-service/test/email/dengue/email-phl-dengue.test.ts
services/API-service/test/email/dengue/test-dengue-scenario.helper.ts
services/API-service/test/email/flash-flood/email-mwi-flash-flood.test.ts
services/API-service/test/email/flash-flood/test-flash-flood-scenario.helper.ts
services/API-service/test/email/malaria/email-eth-malaria.test.ts
services/API-service/test/email/malaria/test-malaria-scenario.helper.ts
services/API-service/test/helpers/utility.helper.ts

test: add api test for flash flood, dengue, and malaria

---

docker-compose.yml

Revert geoserver version update done in [AB#27339](https://dev.azure.com/redcrossnl/IBF%20System/_workitems/edit/27339).
This was tested and reviewed by @gulfaraz and @RubenGeo.
The testing did not include roads and building layers which require [Postgis access via Geoserver](https://stackoverflow.com/questions/76946371/geoserver-parametrized-postgis-database-connection-fails-after-upgrade-from-kart).

fix: revert geoserver version

---

interfaces/IBF-dashboard/src/app/pipes/compact.pipe.ts
services/API-service/src/api/notification/email/html/body-total-affected-available.html
services/API-service/src/shared/helper.service.ts

1. Copy update in email, use _approximately_ prefix instead of _approx._
2. Use 2 max. significant digits for percentages
This PR is a follow up on the design review in https://github.com/rodekruis/Anticipatory-Action/issues/644
1. Generate and check for this change in the email

fix: update copy in email and dashboard

---

interfaces/IBF-dashboard/src/app/components/logos/logos.component.scss

Logos in header should stack horizontally and not vertically.

fix: logos should stack horizontally and not vertically

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/dialogue-turn/dialogue-turn.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.scss
interfaces/IBF-dashboard/src/assets/i18n/en.json

1. A fix for the slow and breaking UI because of the badly configured for loops since the upgrade to ng-18.
2. Make spacing consistent in the chat component.
1. Try loading all the country-hazard combinations. Before this fix, typhoon and epidemics caused the browser tab to crash due to memory limits.
2. Check the spacing of the chat component in smaller window sizes. I tested against the lg, md, sm and xs breakpoints.

fix: use unique id for for loop

---

services/API-service/src/api/event/event.service.ts
services/API-service/test/email/flash-flood/test-flash-flood-scenario.helper.ts
services/API-service/test/email/typhoon/test-typhoon-scenario.helper.ts

Restrict to one event per region.
- This causes event names to be duplicated.

fix: remove group by on event trigger value

---

interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.html
interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.scss
interfaces/IBF-dashboard/src/app/components/disclaimer-approximate/disclaimer-approximate.component.html

This PR include style changes in the aggregates component as per [design review in this comment](https://github.com/rodekruis/Anticipatory-Action/issues/644#issuecomment-2345444530).
1. I've used tailwind classes where possible.
2. Here is the screenshot for reference. Note that there is no gap between the icon and the row line.

fix: aggregates icon style

---

interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.html
interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.scss
interfaces/IBF-dashboard/src/app/components/disclaimer-approximate/disclaimer-approximate.component.html
interfaces/IBF-dashboard/src/app/pipes/compact.pipe.ts
services/API-service/src/shared/helper.service.ts

This PR includes follow up changes on design feedback for https://github.com/rodekruis/Anticipatory-Action/issues/644
1. Show whole numbers for percentage values.
2. Update functions so that,
* 0 becomes 0
* 2 becomes < 10
* 12 becomes < 20
* 20 becomes 20
* 56 becomes 60
* 297 becomes 300
* 462 becomes 460
* 1000 becomes 1K
* 4200 becomes 4.2K
* 225305 becomes 230K
* 79136946 becomes 79M
* negative numbers become 0
1. For testing, I set `value = 12` at the start of the transform function.

fix: prefix for compact numbers

---

services/API-service/src/api/event/event.service.ts

This PR includes a fix to a suspicious logic I found in event service.
https://github.com/rodekruis/IBF-system/blob/c377b55f4e4e3074a4031bc13a96627128a676cd/services/API-service/src/api/event/event.service.ts#L861-L894
The function checks for an updated `triggerValue` and assigns it the `eventArea` object.
But it does not push this to the database UPDATE query.
I have not found the symptoms of this error. I found the logic suspicious so made the _fix_. If it's difficult to identify any symptoms I understand it will be difficult to review. I think it's better to have the _fix_ and deal with those potentially unintended consequences rather than ignore this.

fix: suspicious logic to update triggerValue

---

interfaces/IBF-dashboard/package-lock.json
interfaces/IBF-dashboard/package.json
interfaces/IBF-dashboard/src/app/components/chat/chat.component.ts
interfaces/IBF-dashboard/src/app/components/user-state/user-state.component.html
interfaces/IBF-dashboard/src/app/components/user-state/user-state.component.ts
interfaces/IBF-dashboard/src/app/pages/dashboard/activation-log/activation.log.page.html
interfaces/IBF-dashboard/src/app/pages/dashboard/dashboard-routing.module.ts
interfaces/IBF-dashboard/src/app/pages/dashboard/dashboard.module.ts
interfaces/IBF-dashboard/src/app/pages/dashboard/dashboard.page.html
interfaces/IBF-dashboard/src/app/pages/dashboard/status-report/status-report.page.html
interfaces/IBF-dashboard/src/app/pages/dashboard/status-report/status-report.page.scss
interfaces/IBF-dashboard/src/app/pages/dashboard/status-report/status-report.page.ts
interfaces/IBF-dashboard/src/app/services/api.service.ts
interfaces/IBF-dashboard/src/app/services/event.service.ts
interfaces/IBF-dashboard/src/assets/i18n/en.json
services/API-service/.eslintrc.js

PR for item #1520. Decided to implement this by making a separate page in portal itself, accessible through dev-menu.

Feat.status page

---

e2e/Pages/AggregateComponenet.ts
e2e/tests/AggregatesSection/AllAggregatesComponentsPresentNotrigger.spec.ts
interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.html
services/API-service/test/helpers/utility.helper.ts

Adds assertions for all elements in Aggregates section.

Feat.add e2e test for aggregates section

---

services/API-service/src/api/event/event.service.ts

PR resolves #1575. 
1. First observation is that this bug derives from our mock setup, where all mock data for all admin-areas is repeated for every event, instead of trimming down each event's mock data to only the admin-areas of that event. The reason for this is because it's easier this way, because we'd have to go through all the mock files to do this trimming. Still, it would be better to do that. This same situation should not occur in production, because there the pipeline will actually only upload the admin-areas belonging to that event.
2. That being said, this can and should also additionally be solved by filtering in the GET query code on event if available. This solves the issue, and is the better fix anyway. So opting to not also clean up the mock data. Feel free to disagree.

fix: area speech bbubble appears twice

---

e2e/Pages/LoginPage.ts
e2e/Pages/TimelineComponent.ts
e2e/Pages/UserStateComponent.ts
e2e/tests/Timeline/TimelineInactiveInNotrigger.spec.ts
e2e/tests/UserState/SuccessfullyLogOut.spec.ts
interfaces/IBF-dashboard/src/app/pages/login/login.page.html

Adds assertion for disabled attribute of timeline component in no-trigger state

Feat.add e2e test for timeline inactive

---

services/API-service/src/scripts/json/countries.json

Final chore of #1554 .
Reverses multi-threshold settings in IBF-portal for other countries then UGA and ZMB. In practice the only thing this achieves (on top of the multi-thresholds settings being reversed already in the pipeline) is that the map legend shows only 2 Glofas stations items instead of 4 for those  countries.

feat: reverse multi-threshold other countries

---

interfaces/IBF-dashboard/src/app/components/map/map.component.ts

Resolves [#857](https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=82176000&issue=rodekruis%7CAnticipatory-Action%7C857)
1. There are multiple strange things at work here. I went for the simplest solution to make sure not to meddle with anything not fully understood. Namely, in the front-end eventName was not passed in the GET /triggered-areas call, because it wasn't set yet at the time of the call. By reversing 2 pieces of code this is fixed. This new order is actually in line with the order of 2 other occurences of the same 2 method calls.
2. I tried to go a step further by eliminating the handleTimestepButtonClick call in all 3 occurences, and instead editing the subscription in timeline.service to also call loadTimestepButtons in onManualEventStateChange. But …

fix: make triggered-areas api-call after eventName is set

---

services/API-service/src/scripts/scripts.service.ts

Resolves [bug 859](https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=82194439&issue=rodekruis%7CAnticipatory-Action%7C859)
1. I basically reversed the previous edit on this same line of code, which was - according to the commit message - done to fix ZWE mock. But this code is within an IF, which specifically excludes ZWE.
2. So I reversed it and checked both for Ethiopia (fixes the bug) and for Zimbabwe (still works fine).
3. This is a mock only bug. Production pipeline should take care of not sending any data for more than 3 months leadTime.

fix: do not send any mock exposure data when leadTime > 3 months

---

interfaces/IBF-dashboard/src/app/pipes/compact.pipe.ts
services/API-service/src/api/notification/email/mjml.service.ts
services/API-service/src/api/notification/email/mjml/body-event.ts
services/API-service/src/api/notification/email/mjml/event-admin-area-table.ts
services/API-service/src/api/notification/helpers/mjml.helper.ts
services/API-service/src/api/notification/notification-content/notification-content.service.ts
services/API-service/src/shared/helper.service.ts

This PR is a result of [feedback](https://github.com/rodekruis/Anticipatory-Action/issues/880) from @gal-agmon on #1515
Compact numbers in email consider number format. This changes PHL typhoon emails,
Before this PR, https://us18.campaign-archive.com/?u=e71f3b134823403aa6fe0c6dc&id=ce2d4c8cfb
After this PR, https://us18.campaign-archive.com/?u=e71f3b134823403aa6fe0c6dc&id=44951c89fb

fix: compact number in email should consider format

---

interfaces/IBF-dashboard/src/app/components/export-view-popover/export-view-popover.component.html
interfaces/IBF-dashboard/src/app/components/ibf-guide-popover/ibf-guide-popover.component.html
tests/e2e/Pages/ChatComponent.ts
tests/e2e/tests/ChatSection/AllChatActionButtonsActiveInNoTrigger.spec.ts

Adds test that validates all chat action buttons.

Add e2e test for chat buttons

---

interfaces/IBF-dashboard/src/app/components/map/map.component.ts
interfaces/IBF-dashboard/src/app/components/matrix/matrix.component.html
interfaces/IBF-dashboard/src/app/services/point-marker.service.ts
tests/e2e/Pages/DashboardPage.ts
tests/e2e/Pages/MapComponent.ts
tests/e2e/tests/AggregatesSection/AggregatesHasDynamicTitle.spec.ts
tests/e2e/tests/Map/AssertMapFunctionalitiesNotrigger.spec.ts
tests/e2e/tests/Map/MapFunctionalitiesNotrigger.spec.ts

Adds e2e test for map functionalities in no-trigger mode

Add e2e test for map functionalities in no-trigger mode

---

interfaces/IBF-dashboard/src/app/services/event.service.ts

Correctly skip national view also if only warning events

fix: skip typhoon national view if 2 warning events

---

.github/workflows/workflow.yml

The e2e and integration tests must only run when we change the dashboard or API-service.

ci: run e2e and integration tests only when api-service or dashboard changes

---

interfaces/IBF-dashboard/src/app/components/about-btn/about-btn.component.spec.ts
interfaces/IBF-dashboard/src/app/components/activation-log-button/activation-log-button.component.spec.ts
interfaces/IBF-dashboard/src/app/components/change-password-popover/change-password-popover.component.spec.ts
interfaces/IBF-dashboard/src/app/components/community-notification-popup/community-notification-popup.component.spec.ts
interfaces/IBF-dashboard/src/app/components/export-view/export-view.component.spec.ts
interfaces/IBF-dashboard/src/app/components/ibf-guide-button/ibf-guide-button.component.spec.ts
interfaces/IBF-dashboard/src/app/components/login-form/login-form.component.spec.ts
interfaces/IBF-dashboard/src/app/components/user-state/user-state.component.spec.ts

Removes warnings in frontend tests.
I noticed 2 tests are skipped using `xit`. These need to be unskipped and the errors resolved.

test: remove CUSTOM SCHEMA warnings

---

.github/actions/e2e/action.yml
.github/actions/integration/action.yml

Extend waiting time from 60s to 90s, as it seems e2e and integration tests are failing at that step and when I open the docker logs, they run until almost but not completely the end (the line saying 'Nest application successfully started').

ci: extend wait time startup

---

interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/app/services/eap-actions.service.ts
interfaces/IBF-dashboard/src/app/services/event.service.ts
interfaces/IBF-dashboard/src/app/types/triggered-area.ts
services/API-service/src/api/event/event.service.ts
services/API-service/src/api/notification/email/mjml/event-admin-area-table.ts
services/API-service/src/api/notification/notification-content/notification-content.service.ts
services/API-service/src/shared/data.model.ts

- Resolves [issue 889](https://github.com/rodekruis/Anticipatory-Action/issues/889). In the end by filtering in the front-end, similar to how the email list is filtered. 
- This solves the typhoon issue of showing 1647 areas for warning events.
- For floods, we're accepting for now that this means that the map will still show more areas potentially than the area list. At least the area list coincides with the email.
- Additionally, calculate aggregate count based on the filtered array, not on separate backend property.
- Unrelated, but remove outdated split by alertClass in area-list. 

Fix.filter area list exposed only

---

tools/deploy.sh

Remove integration test on deploy

fix: rm integration tests from deploy script

---

.github/workflows/workflow.yml
services/API-service/package.json
services/API-service/src/api/user/user.service.spec.ts

closes #1603 
@gulfaraz: @jannisvisser and I decided to add a test on `generateJWT` because:
- other functionalities are already covered by API tests
- the remaining non-tested methods in the service are just database calls and we felt they didn't need a unit test

test: add user module unit test

---

interfaces/IBF-dashboard/src/app/components/layer-control-info-popover/layer-control-info-popover.component.html
tests/e2e/Pages/MapComponent.ts
tests/e2e/tests/Map/InfoIconsAreInteractiveInLayerComponent.spec.ts

Adds e2e test for checking interactions with map layer info icons

Add e2e test for info icons interactions

---

interfaces/IBF-dashboard/eslint.config.js
interfaces/IBF-dashboard/src/app/components/leaflet-popup/glofas-station-popup-content/glofas-station-popup-content.component.html
interfaces/IBF-dashboard/src/app/components/leaflet-popup/glofas-station-popup-content/glofas-station-popup-content.component.ts
interfaces/IBF-dashboard/src/app/models/poi.model.ts

Resolves [issue 1798](https://github.com/rodekruis/IBF-system/issues/1798)
1. The issue was that forecastReturnPeriod could have value '0' (as string), and was therefore not blocked by the current 'falsy' check. Adding the '>0' works if forecastReturnPeriod is number or string. (but good to check)
2. Also addressed some of the eslint warnings of the touched files.

fix: only show RP if > 0 + linting fixes

---

services/API-service/migration/1732538758226-StaticDataActiveBoolean.ts
services/API-service/src/api/lines-data/lines-data-views.entity.ts
services/API-service/src/api/lines-data/lines-data.entity.ts
services/API-service/src/api/lines-data/lines-data.service.ts
services/API-service/src/api/point-data/point-data.entity.ts
services/API-service/src/api/point-data/point-data.service.ts

Part of [Blantyre issue](https://github.com/rodekruis/Anticipatory-Action/issues/926)
- Specifically, on updating static point/lines data we used to delete existing point/lines for the given country and layer.
- But this ran into FK constraint erros when there were dynamic records associated with these.
- So instead I now added an 'active' column, which is true by default / for new uploaded ones, and instead of delete we turn those to active: false.
- This way the dynamic data associated with it can just stay in the db for the sake of archive.
1. Please also review https://github.com/rodekruis/IBF-system/wiki/Updating-static-data

fix: deactivate instead of delete when updating point/lines data

---

docs/VM_SETUP.md

This PR is a follow-up on #1602 based on dev experience in the demo VM.
I updated the VM SETUP doc with steps to install the SSL certificate.
These are the commands I ran on the demo VM. These are valid today but can change so I also included the [link to the source](https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal) of these commands. [Certbot](https://certbot.eff.org/) reads the existing nginx config and reconfigures it to include SSL certificates from [LetsEncrypt](https://letsencrypt.org/).

docs: add certbot steps to VM SETUP doc

---

tests/e2e/tests/Map/DefaultLegendLayersInTriggeredFlood.spec.ts
tests/e2e/tests/Map/DefaultMarkersVisibleFloodsTrigger.spec.ts

Adds E2E test for default markers in floods trigger mode (Red, Orange and Yellow).

Add e2e test for default markers in triggered floods

---

interfaces/IBF-dashboard/src/app/components/matrix/matrix.component.html
tests/e2e/Pages/MapComponent.ts
tests/e2e/tests/Map/DefaultLegendLayersInTriggeredFlood.spec.ts
tests/e2e/tests/Map/ExposedPopulationVisibleInTrigger.spec.ts

Adds test for default triggered layers Floods

Add e2e test for default flood trigger layers

---

tests/e2e/tests/AggregatesSection/AggregatesHasDynamicTitle.spec.ts
tests/e2e/tests/AggregatesSection/AggregatesShouldNotBeZeroInTriggerState.spec.ts
tests/e2e/tests/AggregatesSection/AllAggregatesComponentsPresentNotrigger.spec.ts
tests/e2e/tests/AggregatesSection/ValidateAggregatesInfoButtons.spec.ts
tests/e2e/tests/ChatSection/AllChatActionButtonsActiveInNoTrigger.spec.ts
tests/e2e/tests/ChatSection/AllChatComponentsPresentNotrigger.spec.ts
tests/e2e/tests/ChatSection/ChatPredictionButtonActive.spec.ts
tests/e2e/tests/ChatSection/TriggerStateShouldHaveWarningEvents.spec.ts
tests/e2e/tests/Dashboard/AllElementsPresentNoTrigger.spec.ts
tests/e2e/tests/DisasterType/AllDisasterTypeComponentsPresentNotrigger.spec.ts
tests/e2e/tests/DisasterType/SwitchBetweenDisasterType.spec.ts
tests/e2e/tests/Map/AlertThresholdIsVisibleInLegend.spec.ts
tests/e2e/tests/Map/AlertThresholdLinesAreNotVisibleNoTrigger.spec.ts
tests/e2e/tests/Map/AllMapComponentsPresentNotrigger.spec.ts
tests/e2e/tests/Map/AssertAllSelectedCheckboxesLayersArePresent.spec.ts
tests/e2e/tests/Map/AssertMapFunctionalitiesNotrigger.spec.ts
tests/e2e/tests/Map/AssertNoMaxWarningGlofasMarkersVisible.spec.ts
tests/e2e/tests/Map/DefaultMarkersVisibleFloodsTrigger.spec.ts
tests/e2e/tests/Map/GlofasStationsVisibleNoTrigger.spec.ts
tests/e2e/tests/Timeline/TimelineComponentPresentNotrigger.spec.ts
tests/e2e/tests/Timeline/TimelineInactiveInNotrigger.spec.ts
tests/e2e/tests/UserState/AllUserStateComponentsPresentNotrigger.spec.ts
tests/e2e/tests/UserState/SuccessfullyLogOut.spec.ts

Adds test for aggregated number of events to be more then 0 when in trigger mode.

Add E2E for Triggered agregates

---

interfaces/IBF-dashboard/src/app/components/matrix/matrix.component.html
interfaces/IBF-dashboard/src/app/services/map.service.ts
tests/e2e/README.md
tests/e2e/tests/AggregatesSection/AggregatesHasDynamicTitle.spec.ts

Resolves [AB#31737](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/31737)

Fix.toggle off glofas layer

---

interfaces/IBF-dashboard/src/app/pages/dashboard/dashboard.page.html
tests/e2e/Pages/AggregatesComponent.ts
tests/e2e/testData/styles.enum.ts
tests/e2e/tests/AggregatesSection/AggregatesHeaderShouldBePurpleInTriggerState.spec.ts

[AB#32403](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32403)
Adds test for checking if correct colour is assigned to Aggregates by class.
The idea was to catch the full colour code but I added a bit simpler solution without digging into the "color" value itself. Let me know if this is sufficient.
notes from my discussion with Gulfaraz:
```
const dashboardElement = document.getElementById('ibf-dashboard-interface');
.no-alert [data-test].aggregates-header === #758399
.no-alert [data-test].aggregates-footer === #758399
.trigger-alert [data-test].aggregates-header === #adasda
.trigger-alert [data-test].aggregates-footer === #adasda
{
trigger-color:#adasda
no-alert-color: #asdasd
}
```

Feat.add e2e test header colour in trigger is purpule

---

.github/workflows/workflow-push.yml
package.json

[AB#32464](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32464)
Bump version action failed on previous PR merge because the push to master (of package.json version upgrade) was blocked because of the implemented status checks.

chore: satisfy status checks when pushing version upgrade to master

---

interfaces/IBF-dashboard/src/app/components/logos/logos.component.html
interfaces/IBF-dashboard/src/app/components/user-state/user-state.component.html
tests/e2e/Pages/UserStateComponent.ts
tests/e2e/tests/UserStateComponent/UserStateComponentVisible.ts

Fix one e2e test that was failing after the Playwright framework refactor.
I have switched the data-testids that were used for selecting the locators. It seems that they were not visible anymore after the refactor even tho there seems to be no connection between the refactor and testids. I have reused old ids by adding playwright readable format to them 'data-testid' instead of 'data-test'. Also I refactored the test itself to use those ids correctly.

Un-skip e2e test

---

tests/e2e/Pages/MapComponent.ts

Fixes random failures of the test when locator couldn't be found and actions were executed in random order.
Added:
1. Await for domContentLoaded
2. Await for networkIdle
3. 200ms await before hovering over the map

Fix flaky map/ legend/ aggregates e2e test

---

tests/e2e/Pages/ChatComponent.ts
tests/e2e/tests/ChatComponent/ChatComponentVisible.ts
tests/e2e/tests/DashboardPage/DashboardPageVisible.ts
tests/e2e/tests/ScenarioNoTrigger.spec.ts

[AB#32980](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/32980)
Fixes one more occurrence of the timestamp issue earlier fixed somewhere else. I now also checked for more similar cases, but there were none. @Piotrk39 FYI. I'm already merging this, so other PRs are not blocked by this any more, but just tagging you so you're aware towards the future.

fix: flaky tests because of timestamp AB#32980

---

docker-compose.yml
services/API-service/geoserver-volume/geoserver-layers/postgis_db/buildings_MWI/featuretype.xml
services/API-service/geoserver-volume/geoserver-layers/postgis_db/buildings_MWI/layer.xml
services/API-service/geoserver-volume/geoserver-layers/postgis_db/roads_MWI/featuretype.xml
services/API-service/geoserver-volume/geoserver-layers/postgis_db/roads_MWI/layer.xml
tests/e2e/Pages/MapComponent.ts

- See [AB#33134](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/33134)
- The other changes are not related, but the roads/buildings layers still contained a parameter which wasn't used anymore in the view code.

chore: upgrade geoserver AB#33134

---

services/API-service/src/api/admin-area/services/event-area.service.ts
services/API-service/src/api/event/event.service.ts

1. Use variable in interpolated string instead of hardcoded values
2. Include warnings in deeper areas
3. Minor formatting
Skipping review coz we verified the fix in person and the other changes are minor.

fix: format changes

---

services/API-service/src/api/process-pipeline/process-pipeline.controller.ts
services/API-service/src/api/process-pipeline/process-pipeline.service.ts
tests/integration/helpers/API-service/dto/events-process.dto.ts
tests/integration/helpers/utility.helper.ts
tests/integration/tests/events/process.test.ts

This PR adds `noNotifications` to `POST /events/process` events.
[Context](https://teams.microsoft.com/l/message/19:bdb9d621f18c48c7917e545bf6d7aabe@thread.v2/1740756319179?context=%7B%22contextType%22%3A%22chat%22%7D)

feat: add noNotifications query param to POST /events/process

---

interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/app/mocks/event-state.mock.ts
interfaces/IBF-dashboard/src/app/services/alert-area.service.ts
interfaces/IBF-dashboard/src/app/services/api.service.ts
interfaces/IBF-dashboard/src/app/services/event.service.ts
services/API-service/src/api/event/event.controller.ts
services/API-service/src/api/event/event.service.ts
services/API-service/src/shared/data.model.ts
tests/integration/helpers/utility.helper.ts
tests/integration/tests/events/set-trigger.test.ts

- Rough idea for moving the event-aggregates calculation to the front-end as discussed. 
- By making GET /alert-areas content a part of GET /event.
- This is not fully ready, as - if agreed - it needs some more cleaning up. Especially in the alert-area.service, as there is not really a reason to add a subscription to AlertAreas any more, if this data is already available earlier in eventState.
- to do also: fix integration test
- tied this to separate task [AB#34525](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34525)

refactor: calculate event aggregates in front-end AB#34119

---

interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.ts
interfaces/IBF-dashboard/src/app/mocks/event-state.mock.ts
interfaces/IBF-dashboard/src/app/services/alert-area.service.ts
interfaces/IBF-dashboard/src/app/services/api.service.ts
interfaces/IBF-dashboard/src/app/services/event.service.ts
interfaces/IBF-dashboard/src/assets/i18n/en.json
services/API-service/module-dependencies.md
services/API-service/src/api/admin-area/admin-area.module.ts
services/API-service/src/api/admin-area/admin-area.service.ts
services/API-service/src/api/disaster-type/disaster-type.service.ts
services/API-service/src/api/event/enum/alert-level.enum.ts
services/API-service/src/api/event/event.controller.ts
services/API-service/src/api/event/event.module.ts
services/API-service/src/api/event/event.service.spec.ts
services/API-service/src/api/event/event.service.ts
services/API-service/src/api/metadata/metadata.module.ts
services/API-service/src/api/metadata/metadata.service.ts
services/API-service/src/api/notification/dto/content-event-email.dto.ts
services/API-service/src/api/notification/email/mjml/event-admin-area-table.ts
services/API-service/src/api/notification/notification-content/notification-content.module.ts
services/API-service/src/api/notification/notification-content/notification-content.service.ts
services/API-service/src/api/notification/whatsapp/whatsapp.module.ts
services/API-service/src/api/notification/whatsapp/whatsapp.service.ts
services/API-service/src/scripts/mock-helper.service.ts
services/API-service/src/shared/data.model.ts
tests/integration/helpers/utility.helper.ts
tests/integration/tests/events/set-trigger.test.ts

I’m stuck on the aggregates and admin area data (static and dynamic).
The dead-ends I hit,
- [getEventAreaAggregatesPerIndicator](https://github.com/rodekruis/IBF-system/blob/2a29517b2e98b05a10e570dd1074ef3de4b5c1ad/services/API-service/src/api/admin-area/services/event-area.service.ts#L215)
- [getEventAreaDynamicData](https://github.com/rodekruis/IBF-system/blob/2a29517b2e98b05a10e570dd1074ef3de4b5c1ad/services/API-service/src/api/admin-area/services/event-area.service.ts#L173)
- [getEventAreas](https://github.com/rodekruis/IBF-system/blob/2a29517b2e98b05a10e570dd1074ef3de4b5c1ad/services/API-service/src/api/admin-area/services/event-area.service.ts#L76)
- [getEventAreaAggregates](https://github.com/rodekruis/IBF-system/blob/2a29517b2e98b05a10e570dd1074ef3de4b5c1ad/services/API-service/sr …

feat: unset warning

---

services/API-service/src/api/admin-area/admin-area.service.ts

Don't join events of wrong disaster type to admin-areas.

fix: only join event data of correct disaster-type AB#34736

---

services/API-service/src/api/notification/dto/content-event-email.dto.ts
services/API-service/src/api/notification/email/email.service.ts
services/API-service/src/api/notification/email/mjml.service.ts
services/API-service/src/api/notification/email/mjml/body-event.ts
services/API-service/src/api/notification/email/mjml/event-admin-area-table.ts
services/API-service/src/api/notification/notification-content/notification-content.service.ts
services/API-service/src/shared/utils.ts

Show different advisory in warning email that can be set to trigger. See [AB#34603](https://dev.azure.com/redcrossnl/9e7ca3cc-bb97-4471-a25c-fd9787af0fe8/_workitems/edit/34603).

feat: show different advisory for set-trigger warning in email

---

services/API-service/.gitignore
services/API-service/src/api/notification/email/email.service.ts
services/API-service/src/middleware/logger.middleware.ts

1. Mailchimp sends its error messages with an error prefix. We can remove our prefix to avoid duplication.
2. In DEBUG mode, we generate email in HTML files. These must be added to .gitignore.
3. Write a log to indicate that the API service has received and is processing a request.

Refactor.mailchimp error

---

services/API-service/package.json
services/API-service/src/api/user/dto/create-user.dto.ts
services/API-service/src/api/user/dto/login-user.dto.ts
services/API-service/src/api/user/user.model.ts
services/API-service/src/config.ts
services/API-service/src/scripts/scripts.controller.ts
services/API-service/src/scripts/seed-helper.ts
services/API-service/src/scripts/seed-init.ts
services/API-service/src/scripts/seed-prod.ts

This PR is a follow-up on https://github.com/rodekruis/IBF-system/pull/2168
It includes,
- Add truncate flag to seed init
- needed for `/api/scripts/reset`
- this allows running seed init without seed prod in `prestart:dev`
- Use clearer log message in seed prod.
- _Seeding production data..._ implied more than what it was doing _Seed admin user..._
- Move dunant email to the config file
- minor refactor so that we don't have to file search through the repo to find its usage
Seed init is an alternative to seed prod. Either is called only once when the database is empty. They are separate because seed init is reused for `/api/scripts/reset`
If my implementation works, we don't have to reset manually each time we load up a new IBF instance. This is mostly for dev, but it happens often, so …

build: seed init with truncate

---

services/API-service/src/api/admin-area-data/dto/admin-area-data.dto.ts
services/API-service/src/api/admin-area/admin-area.controller.ts
services/API-service/src/api/admin-area/admin-area.entity.ts
services/API-service/src/api/admin-area/admin-area.service.ts
services/API-service/src/api/admin-area/dto/admin-area.dto.ts
services/API-service/src/api/admin-area/dto/delete-admin-areas.dto.ts
services/API-service/src/api/admin-area/dto/upload-admin-areas.dto.ts
services/API-service/src/api/admin-area/event-area.entity.ts
services/API-service/src/api/admin-area/services/event-area.service.ts
services/API-service/src/api/point-data/point-data.controller.ts
services/API-service/src/api/point-data/point-data.service.ts
services/API-service/src/api/typhoon-track/typhoon-track.controller.ts
services/API-service/src/api/typhoon-track/typhoon-track.entity.ts
services/API-service/src/api/typhoon-track/typhoon-track.service.ts
services/API-service/src/api/waterpoints/waterpoints.controller.ts
services/API-service/src/api/waterpoints/waterpoints.service.ts
services/API-service/src/config.ts
services/API-service/src/scripts/dto/mock-input.dto.ts
services/API-service/src/scripts/dto/reset.dto.ts
services/API-service/src/shared/data.model.ts
services/API-service/src/shared/geo.model.ts
services/API-service/src/shared/helper.service.ts

This PR includes refactors on #2190.
1. remove unnecessary use of ApiConsumes
2. use PLACEHOLDER_SECRET for shared string
3. use AdminAreaParams interface
4. use express Response type
5. update swagger descriptions
6. use typeorm geojson types
7. use bulk upsert
8. clean up unnecessary console.logs

refactor: allow admin area update

---

interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.html
interfaces/IBF-dashboard/src/assets/i18n/en.json
tests/e2e/Pages/AggregatesComponent.ts

According to bug [AB#35929](https://dev.azure.com/redcrossnl/IBF/_workitems/edit/35929), event area aggregates should show 0 instead of NA.
The dashboard used to show the aggregate value received from the API, or fall back to NA to indicate that the value was unavailable.
Since event areas,
1. `/admin-areas/aggregates` API does not return a list of admin areas.
2. When events are found, the API returns a list of aggregate values. The dashboard shows the values (as expected).
3. When no events are found, the API returns an empty list. The dashboard falls back to NA (because no values in the API response).
I considered the following solutions,
1. The API should return a list of aggregate values, with aggregate value 0. The aggregates API response requires 3 properties,
```json
{ …
```

fix: event area aggregates should show 0 instead of NA

---

services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.ts
services/API-service/src/api/admin-area/admin-area.service.ts
services/API-service/src/api/admin-area/services/event-area.service.ts
services/API-service/src/api/disaster-type/const/disaster-type.const.ts
tests/integration/helpers/API-service/const/disaster-type.const.ts
tests/integration/tests/admin-areas/admin-areas.assertions.ts
tests/integration/tests/admin-areas/admin-areas.test.ts

- adds drought as event-area disaster-type
- sets up a const to define which disaster-type have event-areas
- small fix needed on eventName for drought
1. I checked trigger and no-trigger for each disaster-type
2. This does not include performance check on drought yet. But that can be separate. The refactor (definining a const) in this PR is needed anyway, we might just take drought ouf of the const array.

Feat.event areas drought

---

.github/dependabot.yml

This PR updates the dependabot groups to reduce the number of maintenance PRs.

ci: regroup angular and eslint packages

---

services/API-service/src/api/notification/email/mjml/body-event.ts
services/API-service/src/api/notification/email/mjml/event-admin-area-table.ts

Use text colour for event titles in email. Noticable for low warning.

fix: use text colour for low warning
